### ISSUE TITLE
Permissions error when editing the ARM Settings after fresh install

### ISSUE THREAD

**Issue by shitwolfymakes** [1337-server/automatic-ripping-machine#111]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
In the course of testing my updated Ubuntu scripts (#108), I discovered an oversight in the script, and in the wiki install guides caused by this command:
https://github.com/1337-server/automatic-ripping-machine/blob/889ec2b56870a50968b452fecb11435702706315/scripts/ubuntu-20.04-install.sh#L57
Earlier in the installation, arm.sample.yaml is correctly set to arm as it's owner. However, the `sudo` command in this line invokes the `cp docs/arm.yaml.sample arm.yaml` command as *root*, resulting in arm.yaml having `root` for an owner, leaving it inaccessible to the `armui` process, which runs under `arm` as the owner.

This results in the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/opt/arm/arm/ui/routes.py", line 340, in settings
    with open(arm_cfg_file, "w") as f:
PermissionError: [Errno 13] Permission denied: '/opt/arm/arm/ui/../../arm.yaml'
``` 
 **This command is the source of the permissions error so many users experience after the initial installation, when they try to change the settings**

I'm already working on the Ubuntu scripts, so the fix for this will be included in the larger PR for merging. The other OS install scripts and wiki install guides will need to be updated separately with the remediation below.

I'm also going to make a separate PR in the upstream repo so they have a fix for this as well.

### Environment
Any environment where the setup involves the command `sudo cp docs/arm.yaml.sample arm.yaml` is subject to this issue.

### Remediation
In every install script and wiki article where this appears
```
sudo cp docs/arm.yaml.sample arm.yaml
```
replace it with this
```
sudo cp docs/arm.yaml.sample arm.yaml
sudo chown arm:arm arm.yaml
```

**Comment by 1337-server** [comment]
Wiki updated, and PR was merged. This can now safely be closed, I think. If not, let me know and ill reopen.
