### ISSUE TITLE
database locked

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#27]
since setting up sendmail properly i have noticed that the most common error is that the database is locked. this happens often when i do more than one disk in quick succession. i think this should be easy enough to handle gracefully and simply wait till the database is free.

**Comment by 1337-server** [comment]
There already is a db updater function in utils.py but ARM doesn't fully use it yet for everything.

**Comment by 1337-server** [comment]
Can you post a log so i can try to find what's triggering it ?

**Comment by TomW1605** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 539, in <module>
    db.session.commit()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO job (arm_version, crc_id, logfile, start_time, stop_time, job_length, status, no_of_titles, title, title_auto, title_manual, year, year_auto, year_manual, video_type, video_type_auto, video_type_manual, imdb_id, imdb_id_auto, imdb_id_manual, poster_url, poster_url_auto, poster_url_manual, devpath, mountpoint, hasnicetitle, errors, disctype, label, ejected, updated, pid, pid_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (None, None, 'IT_HAPPENED_ONE_NIGHT_DISC02.log', '2021-03-06 22:42:43.175553', None, None, 'active', None, None, None, None, None, None, None, 'unknown', None, None, None, None, None, None, None, None, '/dev/sr2', '/mnt/dev/sr2', 0, None, 'dvd', 'IT_HAPPENED_ONE_NIGHT_DISC02', 0, 0, 605399, 7925345414209428598)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by 1337-server** [comment]
Would you mind sharing your main.py or a chunk of it around line 539 ?
As that line number doesn't match with any db.session.commits()

**Comment by TomW1605** [comment]
```
535    # put in db
536    job.status = "active"
537    job.start_time = datetime.datetime.now()
538    db.session.add(job)
539    db.session.commit()
540    config = Config(cfg, job_id=job.job_id)
541    db.session.add(config)
542    db.session.commit()
```

this does not line up because of the changes i have made to modify the folder structure. in the version on the repo it is this line https://github.com/1337-server/automatic-ripping-machine/blob/e3d502c77740fc68b7980c4a3ac15463c9db74ee/arm/ripper/main.py#L523
