### ISSUE TITLE
[docker] cfg[RIPMETHOD]: backup not moving files

### ISSUE THREAD

**Issue by 1337-server** [1337-server/automatic-ripping-machine#45]
### Description
if cfg[RIPMETHOD]: backup - files will go to a blackhole 
cfg[RIPMETHOD]: mkv works as intended

### Environment
Ubuntu 20.10
Docker - 2.5.2_docker

### Log file
[AVENGERS_INFINITY_WAR.log](https://github.com/1337-server/automatic-ripping-machine/files/6175141/AVENGERS_INFINITY_WAR.log)

**Comment by 1337-server** [comment]
possible blame lies with incorrect setup instructions
`/scripts/docker_arm_wrapper.sh` sets user and group to root possibly causing permission problems.
It needs updated by the end user to set the correct arm uid in docking container and `/scripts/docker_arm_wrapper.sh`  like so
```
ARM_UID="1001" 
ARM_GID="1001"
```
Needs further testing.

**Comment by 1337-server** [comment]
/scripts/docker_arm_wrapper.sh being set to
```
ARM_UID="$(id -u arm)"
ARM_GID="$(id -g arm)"
```
Still causes an error with utils.move_files, But the file does get created 

```
[20-03-2021 13:20:12] INFO ARM: utils.eject ejecting disc on /dev/sr1
[20-03-2021 13:20:20] DEBUG ARM: main.main New Title is None
[20-03-2021 13:20:20] INFO ARM: main.main Moving Movie /home/arm/movies/Avengers- Infinity War (2018) 161624440197/Avengers- Infinity War.mkv to /home/arm/movies/Avengers- Infinity War (2018) 161624440197
[20-03-2021 13:20:20] DEBUG ARM: utils.move_files Moving files: Job: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f7db6dea760>) (job_id=4) (no_of_titles=9) (video_type=movie) (poster_url_manual=None) (ejected=False) (arm_version=2.5.2_docker) (title=Avengers- Infinity War) (video_type_auto=movie) (devpath=/dev/sr1) (updated=False) (crc_id=b79c4675bb42ec4f) (title_auto=Avengers- Infinity War) (video_type_manual=None) (mountpoint=/mnt/dev/sr1) (pid=1487) (logfile=AVENGERS_INFINITY_WAR_161624439633.log) (title_manual=None) (imdb_id=tt4154756) (hasnicetitle=True) (pid_hash=6500142483078327164) (start_time=2021-03-20 12:46:36.336236) (year=2018) (imdb_id_auto=None) (errors=None) (stop_time=None) (year_auto=2018) (imdb_id_manual=None) (disctype=dvd) (job_length=None) (year_manual=None) (poster_url=https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg) (label=AVENGERS_INFINITY_WAR) (status=transcoding) (poster_url_auto=https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg) 
[20-03-2021 13:20:20] DEBUG ARM: utils.move_files Arguments: /home/arm/movies/Avengers- Infinity War (2018) 161624440197 : /home/arm/movies/Avengers- Infinity War (2018) 161624440197/Avengers- Infinity War.mkv : True : Avengers- Infinity War (2018) : True
[20-03-2021 13:20:20] INFO ARM: utils.move_files Track is the Main Title.  Moving '/home/arm/movies/Avengers- Infinity War (2018) 161624440197/Avengers- Infinity War.mkv' to /home/arm/movies/Avengers- Infinity War (2018)
[20-03-2021 13:20:20] ERROR ARM: main.<module> A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/home/arm/movies/Avengers- Infinity War (2018) 161624440197/Avengers- Infinity War.mkv' -> '/home/arm/movies/Avengers- Infinity War (2018)/Avengers- Infinity War (2018).mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 548, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 394, in main
    utils.move_files(p, track.filename, job, track.main_feature)
  File "/opt/arm/arm/ripper/utils.py", line 933, in move_files
    shutil.move(os.path.join(basepath, filename), m_file)
  File "/usr/lib/python3.8/shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/arm/movies/Avengers- Infinity War (2018)/Avengers- Infinity War (2018).mkv'
[20-03-2021 13:20:20] DEBUG ARM: selector_events.__init__ Using selector: EpollSelector
[20-03-2021 13:20:20] WARNING ARM: NotifyPushBullet._send Failed to deliver payload to PushBullet:Unauthorized - Invalid Token., error=401.
[20-03-2021 13:20:20] DEBUG ARM: selector_events.__init__ Using selector: EpollSelector
[20-03-2021 13:20:20] DEBUG ARM: selector_events.__init__ Using selector: EpollSelector
[20-03-2021 13:20:21] DEBUG ARM: utils.apprise_notify Trying ##########apprise -vv -t "ARM notification" -b "ARM encountered a fatal error processing Avengers- Infinity War. Check the logs for more details. [Errno 13] Permission denied: '/home/arm/movies/Avengers- Infinity War (2018)/Avengers- Infinity War (2018).mkv'" dbus://
[20-03-2021 13:20:22] DEBUG ARM: utils.apprise_notify Trying ##########apprise -vv -t "ARM notification" -b "ARM encountered a fatal error processing Avengers- Infinity War. Check the logs for more details. [Errno 13] Permission denied: '/home/arm/movies/Avengers- Infinity War (2018)/Avengers- Infinity War (2018).mkv'" kde://
[20-03-2021 13:20:22] DEBUG ARM: utils.apprise_notify Trying ##########apprise -vv -t "ARM notification" -b "ARM encountered a fatal error processing Avengers- Infinity War. Check the logs for more details. [Errno 13] Permission denied: '/home/arm/movies/Avengers- Infinity War (2018)/Avengers- Infinity War (2018).mkv'" gnome://
[20-03-2021 13:20:22] DEBUG ARM: utils.apprise_notify Trying ##########apprise -vv -t "ARM notification" -b "ARM encountered a fatal error processing Avengers- Infinity War. Check the logs for more details. [Errno 13] Permission denied: '/home/arm/movies/Avengers- Infinity War (2018)/Avengers- Infinity War (2018).mkv'" windows://
[20-03-2021 13:20:22] DEBUG ARM: utils.notify apprise-config: /home/arm/config/apprise.yaml
[20-03-2021 13:20:22] INFO ARM: utils.eject ejecting disc on /dev/sr1
```

Need to update the wiki to include info about creating or using a user and setting both in ARM docker and the docker_arm_wrapper.sh
