### ISSUE TITLE
devel branch issue

### ISSUE THREAD

**Issue by cpesko** [1337-server/automatic-ripping-machine#50]
Mar 30 19:56:57 zero multipathd[1145]: path checkers took longer than 133 seconds, consider increasing max_polling_interval
Mar 30 19:56:57 zero systemd-udevd[168402]: sr3: Process '/opt/arm/scripts/arm_wrapper.sh sr3' failed with exit code 1.
Mar 30 19:56:57 zero systemd-udevd[168402]: sr3: Process '/opt/arm/scripts/arm_wrapper.sh sr3' failed with exit code 1.
Mar 30 19:56:58 zero multipathd[1145]: pktcdvd0: unusable path (wild) - checker failed
Mar 30 19:56:58 zero multipathd[1145]: pktcdvd1: unusable path (wild) - checker failed
Mar 30 19:56:59 zero multipathd[1145]: pktcdvd2: unusable path (wild) - checker failed
Mar 30 19:56:59 zero python3[168322]: [2021-03-30 19:56:59,827] DEBUG in routes: %d-%m-%Y %H:%M:%S
Mar 30 19:56:59 zero python3[168322]: 10.0.0.45 - - [30/Mar/2021 19:56:59] "#033[37mGET /history HTTP/1.1#033[0m" 200 -
Mar 30 19:56:59 zero multipathd[1145]: pktcdvd3: unusable path (wild) - checker failed
Mar 30 19:57:01 zero python3[168322]: 10.0.0.45 - - [30/Mar/2021 19:57:01] "#033[37mGET /listlogs HTTP/1.1#033[0m" 200 -### Description
[Description of Bug, Feature, Question, etc.]

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)]

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by cpesko** [comment]
Loading log: BLADE_16X9_161716994989.log...
[31-03-2021 05:53:14] INFO ARM: Starting ARM processing at 2021-03-31 05:53:14.161097
[31-03-2021 05:53:14] INFO ARM: Database is up to date
[31-03-2021 05:53:14] INFO ARM: ARM version: 2.5.3_dev
[31-03-2021 05:53:14] INFO ARM: Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
[31-03-2021 05:53:14] INFO ARM: User is: root
[31-03-2021 05:53:14] INFO ARM: Looking for log files older than 1 days old.
[31-03-2021 05:53:14] INFO ARM: Job: BLADE_16X9
[31-03-2021 05:53:14] INFO ARM: Job #5 with PID 191607 is currently running.
[31-03-2021 05:53:14] INFO ARM: Starting Disc identification
[31-03-2021 05:53:14] INFO ARM: Mounting disc to: /mnt/dev/sr3
[31-03-2021 05:53:56] INFO ARM: Disc identified as video
[31-03-2021 05:53:56] ERROR ARM: Pydvdid failed with the error: Path '/mnt/dev/sr3/VIDEO_TS' does not exist.
[31-03-2021 05:53:57] INFO ARM: Disc title Post ident: BLADE_16X9 :  : unknown
[31-03-2021 05:53:57] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "main.py", line 482, in <module>
    main(logfile, job)
  File "main.py", line 200, in main
    have_dupes, crc_jobs = utils.job_dupe_check(job)
  File "/opt/arm/arm/ripper/utils.py", line 774, in job_dupe_check
    title = r[0]['title'] if r[0]['title'] else job.label
KeyError: 0

**Comment by 1337-server** [comment]
Great catch!, i messed up the if statement for this.

I will push a fix
