### ISSUE TITLE
ARM Errors Out When DVD is Not Identified

### ISSUE THREAD

**Issue by heatvent** [1337-server/automatic-ripping-machine#64]
### Description
Errors out when DVD is not identified.  See the log file below.

I would assume it should wait out the 60-second delay so a title search/fix can be done and/or move on to be unidentified.  I am unfortunately starting ARM manually through the command line since I am getting errors when loading a disc ... see my other open issue (https://github.com/1337-server/automatic-ripping-machine/issues/63).  Perhaps this has something to do with this.

For DVDs it recognizes, no issues and everything is normal.

### Environment
Ubuntu Mate 20.04
2.5.3_dev

### Log file

[08-04-2021 20:28:02] DEBUG ARM: identify.metadata_selector provider omdb
[08-04-2021 20:28:02] DEBUG ARM: utils.call_omdb_api omdb - {'Response': 'False', 'Error': 'Movie not found!'}
[08-04-2021 20:28:02] DEBUG ARM: utils.call_omdb_api omdb - call was successful
[08-04-2021 20:28:02] DEBUG ARM: identify.update_job s =======  {'Response': 'False', 'Error': 'Movie not found!'}
[08-04-2021 20:28:02] ERROR ARM: main.<module> A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 481, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 197, in main
    identify.identify(job, logfile)
  File "/opt/arm/arm/ripper/identify.py", line 66, in identify
    res = identify_dvd(job)
  File "/opt/arm/arm/ripper/identify.py", line 187, in identify_dvd
    dvd_info_xml = metadata_selector(job, dvd_title, year)
  File "/opt/arm/arm/ripper/identify.py", line 299, in metadata_selector
    update_job(job, x)
  File "/opt/arm/arm/ripper/identify.py", line 256, in update_job
    new_year = s['Search'][0]['Year']
KeyError: 'Search'
[08-04-2021 20:28:06] DEBUG ARM: models.eject failed to eject/dev/sr0

**Comment by 1337-server** [comment]
I thought it was a very simple fix, but i will need to fix the returns from ombi to match with tmdb.

**Comment by heatvent** [comment]
Thanks ... BTW, how would I update.  I used the unattended install script so do I just copy over the files or something?

Thanks again!

**Comment by 1337-server** [comment]
You should just be able to cs into /opt/arm and run git pull

But if that doesn't work you will need to copy the files over manually to /opt/arm

**Comment by heatvent** [comment]
So I was re-installing ARM on a new OS install which picked up the updated build of ARM.  The erroring out issue seems to be resolved.  I did notice, however, that it seems to go right to transcoding vs waiting 60 seconds for manual input per the ARM settings.  Not sure if that is intended or if it should always delay whether or not the disk was identified.

Thanks!

**Comment by heatvent** [comment]
Spoke too soon.  I tried another title and same issue as before.  I switched to tmdb and the title was found so it waited then proceeded with transcoding as expected.  Will see if there is an unknown for tmdb that has issues if I find one but may be hit or miss.

**Comment by 1337-server** [comment]
Is the output the exact same ?

**Comment by heatvent** [comment]
Here is the error in the logfile ...

`[09-04-2021 16:16:26] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 481, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 197, in main
    identify.identify(job, logfile)
  File "/opt/arm/arm/ripper/identify.py", line 66, in identify
    res = identify_dvd(job)
  File "/opt/arm/arm/ripper/identify.py", line 187, in identify_dvd
    dvd_info_xml = metadata_selector(job, dvd_title, year)
  File "/opt/arm/arm/ripper/identify.py", line 299, in metadata_selector
    update_job(job, x)
  File "/opt/arm/arm/ripper/identify.py", line 256, in update_job
    new_year = s['Search'][0]['Year']
KeyError: 'Search'`

If I switch to TMDB it identifies the disk and moves forward.

**Comment by 1337-server** [comment]
Latest commit should now handle it correctly.

**Comment by heatvent** [comment]
Seems to be working correctly now... thank you!

**Comment by 1337-server** [comment]
Glad its fixed, ill close this. but ill reopen if the issue reappears
